name: issue2hexo

env:
  # Pages Deploy Repo
  PUBLISH_REPOSITORY: cloudswave/cloudswave.github.io
  # GITHUB TOKEN
  GITHUB_TOKEN: ${{ secrets.BLOG_TOKEN }}
on:
  issues:
    # Sufficient to trigger this workflow when an issue is unlabeled, labeled, edited, milestoned
    types: [unlabeled, labeled, edited, milestoned]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor == github.repository_owner }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'    
      # use here
      - uses: zenghongtu/github-issue-to-hexo@v2.0.0
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ## optional below
          milestone: 'publish'
          output: './'
      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'noreply@github.com'
          git pull
          git add .
          git commit -m "update posts"
          git push
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run clean && npm run dist
#       - name: Gulp
#         run: npm run gulp
      - name: Deploy
        uses: cloudswave/hexo-deploy@master
        env:
          PERSONAL_TOKEN: ${{ env.GITHUB_TOKEN }}
          PUBLISH_REPOSITORY: ${{ env.PUBLISH_REPOSITORY }} # The repository the action should deploy to.
          BRANCH: master  # The branch the action should deploy to.
          PUBLISH_DIR: ./public # The folder the action should deploy.
          HEXO_GEN: false


#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ github.token }}
#           publish_dir: ./public
