name: issue2hexo

env:
  PUBLISH_REPOSITORY: cloudswave/cloudswave.github.io
  # GITHUB TOKEN
  GITHUB_TOKEN: ${{ secrets.BLOG_TOKEN }}
on:
  issues:
    # Sufficient to trigger this workflow when an issue is unlabeled, labeled, edited, milestoned
    types: [unlabeled, labeled, edited, milestoned]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor == github.repository_owner }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'    
      # use here
      - uses: zenghongtu/github-issue-to-hexo@v2.0.0
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ## optional below
          milestone: 'publish'
          output: './source/_post/'
      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'noreply@github.com'
          git pull
          git add .
          git commit -m "update posts"
          git push
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: Build and Deploy
        uses: solybum/hexo-deploy@master
        env:
          PERSONAL_TOKEN: ${{ env.GITHUB_TOKEN }}
          PUBLISH_REPOSITORY: ${{ env.PUBLISH_REPOSITORY }} # The repository the action should deploy to.
          BRANCH: master  # The branch the action should deploy to.
          PUBLISH_DIR: ./public # The folder the action should deploy.
# env:
#   # hexo源文件仓库
#   BLOG_SOURCE: cloudswave/blog
#   # issue链接
#   ISSUE_URL: https://github.com/cloudswave/blog/issues
#   # blog部署的页面
#   BLOG: cloudswave/blog
#   # github pages repo
#   PUBLISH_REPOSITORY: cloudswave/cloudswave.github.io
#   # GITHUB TOKEN
#   GITHUB_TOKEN: ${{ secrets.BLOG_TOKEN }}
  
# on:
#   issues:
#     types: [opened, edited]
#   push:
#     branches:    
#       - 'master'
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     # 仓库作者才才能触发
#     if: ${{ github.actor == github.repository_owner }}
#     steps:
#       - name: 拉取hexo源文件
#         uses: actions/checkout@v3
#         with:
#           persist-credentials: 'false'
#           repository: ${{ env.BLOG_SOURCE }}
#           ref: 'master'
#           token: ${{ github.token }}
#       - name: issue生成hexo文章
#         uses: flytam/github-issue-to-hexo@main
#         with:
#           issue_url: ${{ env.ISSUE_URL }}
#           output: 'source/_posts'
#           replace: false # 是否先清空output目录
#       - name: commit hexo源文件
#         run: |
#           echo $(date) > update.md
#           git add .
#           git config user.name "issue-to-hexo bot"
#           git config user.email "test@github.com"
#           git commit -m "Add a post"
#       - name: 推送hexo源文件
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ github.token }}
#           repository: ${{ env.BLOG_SOURCE }}
#       - name: Build and Deploy
#         uses: solybum/hexo-deploy@master
#         env:
#           PERSONAL_TOKEN: ${{ env.GITHUB_TOKEN }}
#           PUBLISH_REPOSITORY: ${{ env.PUBLISH_REPOSITORY }} # The repository the action should deploy to.
#           BRANCH: master  # The branch the action should deploy to.
#           PUBLISH_DIR: ./public # The folder the action should deploy.


#       - name: Cache NPM dependencies
#         uses: actions/cache@v2
#         with:
#           path: node_modules
#           key: ${{ runner.OS }}-npm-cache
#           restore-keys: |
#             ${{ runner.OS }}-npm-cache
#       - name: Install Dependencies
#         run: npm install
#       - name: Build
#         run: npm run dist
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ github.token }}
#           publish_dir: ./public
